"""add resume raw_text and tailor_run table

Revision ID: 16b71d16d303
Revises: 6590f19eb5ba
Create Date: 2026-07-14 19:24:45.784232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16b71d16d303'
down_revision: Union[str, Sequence[str], None] = '6590f19eb5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tailor_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_pick_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('resume_content', sa.String(), nullable=True),
    sa.Column('resume_emphasized_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cover_letter_content', sa.String(), nullable=True),
    sa.Column('cover_letter_emphasized_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_pick_id'], ['job_pick.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('resume', sa.Column('raw_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'raw_text')
    op.drop_table('tailor_run')
    # ### end Alembic commands ###
